// <auto-generated />
namespace DesafioPrevidencia.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdicionarDadosTabelaPerfisInverstidor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionarDadosTabelaPerfisInverstidor));
        
        string IMigrationMetadata.Id
        {
            get { return "202101081706321_AdicionarDadosTabelaPerfisInverstidor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
